// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJb8t0RX2bpjOIIDxpuIPPH46g4Zdi840',
    appId: '1:1053712595641:web:c10052e710482208e23968',
    messagingSenderId: '1053712595641',
    projectId: 'firstapp-5c812',
    authDomain: 'firstapp-5c812.firebaseapp.com',
    storageBucket: 'firstapp-5c812.firebasestorage.app',
    measurementId: 'G-K7M8D8N92V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCj6Yk4zsUAuSrBhJILWeEPUquwwnDQjGE',
    appId: '1:1053712595641:android:6d31bf2ccc7ef3d5e23968',
    messagingSenderId: '1053712595641',
    projectId: 'firstapp-5c812',
    storageBucket: 'firstapp-5c812.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcfycsSblNcw3MG1jFt_1-vLHoC4XOzWU',
    appId: '1:1053712595641:ios:88f92d8a92c56ad3e23968',
    messagingSenderId: '1053712595641',
    projectId: 'firstapp-5c812',
    storageBucket: 'firstapp-5c812.firebasestorage.app',
    iosBundleId: 'com.example.aiProject',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcfycsSblNcw3MG1jFt_1-vLHoC4XOzWU',
    appId: '1:1053712595641:ios:88f92d8a92c56ad3e23968',
    messagingSenderId: '1053712595641',
    projectId: 'firstapp-5c812',
    storageBucket: 'firstapp-5c812.firebasestorage.app',
    iosBundleId: 'com.example.aiProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJb8t0RX2bpjOIIDxpuIPPH46g4Zdi840',
    appId: '1:1053712595641:web:c71ade45338e0beae23968',
    messagingSenderId: '1053712595641',
    projectId: 'firstapp-5c812',
    authDomain: 'firstapp-5c812.firebaseapp.com',
    storageBucket: 'firstapp-5c812.firebasestorage.app',
    measurementId: 'G-88DBB18ZV1',
  );
}
